config/routes.rb
Rails.application.routes.draw do

  devise_for :employees

  devise_scope :employee do
    authenticated :employee do
      root 'employees#profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  resources :employees, only: %i[show update edit] do
    collection do
      get :profile
    end
  end

  resources :tasks do
    member do
      put :complete
      put :take
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_tasks, foreign_key: :creator_id, class_name: 'Task', inverse_of: :employee, dependent: :destroy

  has_many :assigned_tasks, foreign_key: :assignee_id, class_name: 'Task', inverse_of: :employee, dependent: :destroy

  validates :first_name, :last_name, presence: true, length: { maximum: 30 }
  validates :email, uniqueness: true
end

app/models/task.rb
# frozen_string_literal: true

class Task < ApplicationRecord
  STATUSES = { untaken: 0, in_work: 1, complete: 3 }.freeze
  enum status: STATUSES

  scope :completed, -> { where(status: 'complete') }
  scope :in_work, -> { where(status: 'in_work') }
  scope :untaken, -> { where(status: 'untaken') }

  belongs_to :employee, foreign_key: :creator_id, class_name: 'Employee',
                    inverse_of: :created_tasks

  validates :title, :creator_id, :assignee_id, presence: true
  validates :title, length: { maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update) do |user_params|
      user_params.permit(:password, :password_confirmation, :current_password,
                         :first_name, :last_name)
    end

    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit(:email, :password, :password_confirmation,
                         :first_name, :last_name)
    end
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_current_employee, only: %i[update edit profile]
  before_action :authenticate_employee!, only: %i[update edit]

  def profile
    redirect_to unauthenticated_root_path if current_employee.nil?
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def edit; end

  def update
    if @employee.update(employee_params)
      redirect_to @employee, notice: 'Successfully updated'
    else
      render :edit
    end
  end

  private

  def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email,:password, :password_confirmation)
  end

  def set_current_employee
    @employee = current_employee
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_current_task_employee,
  only: %i[edit update destroy complete take]

  def new
    @task = current_employee.created_tasks.create
  end

  def create
    @task = current_employee.created_tasks.create(task_params)

    if @task.save
      redirect_to authenticated_root_path, notice: 'You created new task'
    else
      render :new
    end
  end

  def show
  end

  def edit; end

  def update
    if @task.update(task_params)
      redirect_to current_employee, notice: 'Successfully updated'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy

    redirect_back(fallback_location: authenticated_root_path,
                  notice: 'Task deleted')
  end

  def complete
    @task = Task.find(params[:id])
    @task[:finished_at] = Time.zone.now
    @task.complete!

    redirect_to authenticated_root_path, notice: 'You has finished task'
  end

  def take
    @task = Task.find(params[:id])
    @task[:started_at] = Time.zone.now
    @task.in_work!

    redirect_to authenticated_root_path, notice: 'Lets work!'
  end

  private

  def set_current_task_employee
    @task = current_employee.assigned_tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :description, :assignee_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/application/_header.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button class="navbar-toggle" data-target=".navbar-responsive-collapse" data-toggle="collapse" type="button">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>

    <% if current_employee %>
      <%= link_to 'Task Manager | tecnical test for TODOSISTEMAS', authenticated_root_path, class: ['navbar-brand'] %>
    <% else %>
      <%= link_to 'Task Manager | tecnical test for TODOSISTEMAS', unauthenticated_root_path, class: ['navbar-brand'] %>
    <% end %>

    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to 'Create task', new_task_path if employee_signed_in? %>
        </li>
        <li>
          <%= link_to 'Edit profile', edit_employee_path(@employee) if current_employee == @employee %>
        </li>
        <li>
          <%= link_to 'Logout', destroy_employee_session_path, method: :delete if employee_signed_in? %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/employees/_tasks.html.haml
- tasks.each do |task|
  .col-lg-12
    %section.info
    %section.cards-wrapper
      .card-grid-space
        %a.card{href: "https://codetheweb.blog/2017/10/06/html-syntax/", style: "--bg-img: url(https://images1-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&resize_w=1500&url=https://codetheweb.blog/assets/img/posts/html-syntax/cover.jpg)"}
          %div
            %h1.card-title= task.title
            %p.card-text= task.description
            %p.card-text
              Started: #{task.started_at.to_formatted_s(:short) if task.started_at.present?}
            %p.card-text
              Finished: #{task.finished_at.to_formatted_s(:short) if task.finished_at.present?}
            %br
          - if task.employee == current_employee
            = button_to('complete', complete_task_path(task),
              method: :put,
              class: 'btn btn-primary') if task.status == 'in_work'
            = button_to('Take', take_task_path(task),
              method: :put,
              class: 'btn btn-primary') if task.status == 'untaken'
            = link_to task_path(task), method: :delete do
              %i.fa.fa-trash
            = link_to edit_task_path(task) do
              %i.fa.fa-edit
            -# .date= Time.now
            -# .tags
            -#   .tag HTML

app/views/employees/edit.html.erb
<div class="col-lg-4"></div>
<div class="col-lg-4">
  <div class="panel panel-default devise-bs">
    <div class="panel-heading">
      <h4>Edit Profile</h4>
    </div>
    <div class="panel-body">
      <%= form_for(@employee) do |f| %>
        <%= render partial: 'partials/form_errors', locals: {model: @employee} %>
        <div class="form-group">
          <%= f.label :first_name %>
          <%= f.text_field :first_name, class: 'form-control' %>
          <div class="form-group"></div>
          <%= f.label :last_name %>
          <%= f.text_field :last_name, class: 'form-control' %>
          <div class="form-group"></div>
          <%= f.label :password %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        <%= f.submit 'Submit', class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/employees/profile.html.erb
<div class="text-center">
  <h1>
    <%= @employee.first_name %>
    <%= @employee.last_name %>
  </h1>
</div>
<div class="col-lg-4">
  <h2 class="text-center">Untaken</h2>
  <% if @employee.assigned_tasks.untaken.present? %>
    <%= render partial: 'employees/tasks', locals: { tasks: @employee.assigned_tasks.untaken } %>
  <% else %>
    <h1 class="text-center">No tasks for you</h1>
  <% end %>
</div>
<div class="col-lg-4">
  <h2 class="text-center">In Work</h2>
  <% if @employee.assigned_tasks.in_work.present? %>
    <%= render partial: 'employees/tasks', locals: { tasks: @employee.assigned_tasks.in_work } %>
  <% else %>
    <h1 class="text-center">No tasks in work</h1>
  <% end %>
</div>
<div class="col-lg-4">
  <h2 class="text-center">Completed</h2>
  <% if @employee.assigned_tasks.completed.present? %>
    <%= render partial: 'employees/tasks', locals: { tasks: @employee.assigned_tasks.completed } %>
  <% else %>
    <h1 class="text-center">No completed tasks</h1>
  <% end %>
</div>

app/views/employees/show.html.erb
<div class="text-center">
  <h1>
    <%= @employee.first_name %>
    <%= @employee.last_name %>
  </h1>
</div>
<div class="col-lg-4">
  <h2 class="text-center">Untaken</h2>
  <% if @employee.assigned_tasks.untaken.present? %>
    <%= render partial: 'employees/tasks', locals: { tasks: @employee.assigned_tasks.untaken } %>
  <% else %>
    <h1 class="text-center">No tasks for you</h1>
  <% end %>
</div>
<div class="col-lg-4">
  <h2 class="text-center">In Work</h2>
  <% if @employee.assigned_tasks.in_work.present? %>
    <%= render partial: 'employees/tasks', locals: { tasks: @employee.assigned_tasks.in_work } %>
  <% else %>
    <h1 class="text-center">No tasks in work</h1>
  <% end %>
</div>
<div class="col-lg-4">
  <h2 class="text-center">Completed</h2>
  <% if @employee.assigned_tasks.completed.present? %>
    <%= render partial: 'employees/tasks', locals: { tasks: @employee.assigned_tasks.completed } %>
  <% else %>
    <h1 class="text-center">No completed tasks</h1>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <title>
      <%= content_for?(:title) ? yield(:title) : "SimpleTaskManager" %>
    </title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= render ('header') %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_form_errors.html.haml
- errors = model.errors
- if errors.any?
  .alert.alert-danger
    .lead.buffer-bottom
      #{errors.count}
    %ul
      - errors.full_messages.each do |message|
        %li= message

app/views/tasks/_form.html.erb
<%= form_with(model: @task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control', style: 'height: 150px' %>
  </div>

  <div class="form-group">
    <%= f.label :assignee_id, 'Assign to:' %>
    <%= f.select :assignee_id, options_from_collection_for_select(Employee.all, :id, :email, current_employee.id),
      {}, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-primary' %>
    <%= link_to 'Back', authenticated_root_path, class: 'btn btn-secundary' %>

  </div>

<% end %>

app/views/tasks/edit.html.erb
<div class="row">
  <div class="col-lg-4"></div>
  <div class="col-lg-4 buffer-top">
    <%= render 'form', locals: { employees: @employees} %>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="row">
  <div class="col-lg-4"></div>
  <div class="col-lg-4 buffer-top">
    <%= render 'form', locals: { employees: @employees} %>
  </div>
</div>